---
name: Build images

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  rubocop:
    env:
      BUNDLE_WITHOUT: release
      BEAKER_HYPERVISOR: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Run beaker
        run: bundle exec beaker --provision --dry-run --hosts ubuntu2204-64
      - name: List images
        run: docker images
      - name: List container
        run: docker ps
